# Generated by Django 4.1.7 on 2023-03-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_entrega3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
