# Generated by Django 4.1.7 on 2023-03-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_entrega3', '0002_delete_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('documento', models.IntegerField()),
                ('fecha', models.DateField()),
                ('necesita_medico', models.CharField(max_length=30)),
            ],
        ),
    ]
